name: GramersRankupCoreV2
version: ${project.version}
main: org.kcsup.gramersrankupcorev2.Main
api-version: 1.8.8
description: The second version of the core plugin for the Gramers Rankup Server.
commands:
  rank:
    description: Rank command
  practice:
    description: Practice command
    aliases:
      - prac
  unpractice:
    description: Unpractice command
    aliases:
      - unprac
  warpsign:
    description: Sign command
  lobby:
    description: Lobby Command
    aliases:
      - l
  save:
    description: Save command
  saves:
    description: Saves command
  menu:
    description: Menus command
  warp:
    description: Warp command
  warps:
    description: Warps command
  warpcreate:
    description: Warp Create command
    aliases:
      - warpc
softdepend:
  - WorldEdit
